-- Create core schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS core;

-- Create parcels.test table in core schema
-- Note: In PostgreSQL, the table name is core.parcels_test (schema.table)
-- The "parcels.test" notation from the requirements is interpreted as a table named "parcels_test" in the "core" schema
CREATE TABLE IF NOT EXISTS core.parcels_test (
  id SERIAL PRIMARY KEY,
  tax_sale_id TEXT,
  parcel_id TEXT,
  file_number TEXT,
  remove TEXT,
  notes TEXT,
  years_due TEXT,
  map_parcel TEXT,
  bill TEXT,
  account TEXT,
  property_description TEXT,
  def_in_fifa TEXT,
  def TEXT,
  def_add_street_1 TEXT,
  def_add_street_2 TEXT,
  def_add_city TEXT,
  def_add_state TEXT,
  def_add_zip TEXT,
  dn_add_street_1 TEXT,
  dn_add_street_2 TEXT,
  dn_add_city TEXT,
  dn_add_state TEXT,
  dn_add_zip TEXT,
  crh TEXT,
  crh_add_street_1 TEXT,
  crh_add_street_2 TEXT,
  crh_add_city TEXT,
  crh_add_state TEXT,
  crh_add_zip TEXT,
  occ_add_street_1 TEXT,
  occ_add_street_2 TEXT,
  occ_add_city TEXT,
  occ_add_state TEXT,
  occ_add_zip TEXT,
  lh1 TEXT,
  lh1_add_street_1 TEXT,
  lh1_add_street_2 TEXT,
  lh1_add_city TEXT,
  lh1_add_state TEXT,
  lh1_add_zip TEXT,
  lh1_ref_deed TEXT,
  lh1_deed_info TEXT,
  lh2 TEXT,
  lh2_add_street_1 TEXT,
  lh2_add_street_2 TEXT,
  lh2_add_city TEXT,
  lh2_add_state TEXT,
  lh2_add_zip TEXT,
  lh2_ref_deed TEXT,
  lh2_deed_info TEXT,
  lh3 TEXT,
  lh3_add_street_1 TEXT,
  lh3_add_street_2 TEXT,
  lh3_add_city TEXT,
  lh3_add_state TEXT,
  lh3_add_zip TEXT,
  lh3_ref_deed TEXT,
  lh3_deed_info TEXT,
  ra_registered_agent TEXT,
  ra_registered_agent_title TEXT,
  ra_registered_agent_first TEXT,
  ra_registered_agent_middle TEXT,
  ra_registered_agent_last TEXT,
  ra_address_street_1 TEXT,
  ra_address_street_2 TEXT,
  ra_address_city TEXT,
  ra_address_state TEXT,
  ra_address_zip TEXT,
  ra_phone TEXT,
  m1 TEXT,
  m1_add_street_1 TEXT,
  m1_add_street_2 TEXT,
  m1_add_city TEXT,
  m1_add_state TEXT,
  m1_add_zip TEXT,
  m1_info TEXT,
  m2 TEXT,
  m2_add_street_1 TEXT,
  m2_add_street_2 TEXT,
  m2_add_city TEXT,
  m2_add_state TEXT,
  m2_add_zip TEXT,
  m2_info TEXT,
  m3 TEXT,
  m3_add_street_1 TEXT,
  m3_add_street_2 TEXT,
  m3_add_city TEXT,
  m3_add_state TEXT,
  m3_add_zip TEXT,
  m3_info TEXT,
  ftl TEXT,
  ftl_book_page TEXT,
  gtl TEXT,
  gtl_book_page TEXT,
  dol TEXT,
  dol_book_page TEXT,
  city TEXT,
  city_book_page TEXT,
  legal TEXT,
  ref_deed TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on tax_sale_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_parcels_test_tax_sale_id ON core.parcels_test(tax_sale_id);

-- Create index on parcel_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_parcels_test_parcel_id ON core.parcels_test(parcel_id);
